error[mismatched_arg_count]: this function takes 2 arguments but 3 arguments were supplied
   ┌─ reassigned_variables.lua:14:17
   │
14 │     local function foo(l, m)
   │                    --- note: function defined here
   ·
18 │     foo(1, 2, 3)
   │     ^^^ expected 2 arguments

